
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

climate:
  - platform: mqtt
    name: Palazzetti
    unique_id: palazzetti
    modes:
      - "off"
      - "heat"
    hold_modes:
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
    fan_modes:
      - "Off"
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
      - "High"
      - "Auto"
    mode_command_topic: "homeassistant/climate/palazzetti/modeCmd"
    mode_state_topic: "homeassistant/climate/palazzetti/state"
    mode_state_template: "{{ value_json.mode}}"
    hold_command_topic: "homeassistant/hold/set"
    hold_state_topic: "homeassistant/climate/palazzetti/state"
    hold_state_topic: "{{ value_json.hold}}"
    temperature_command_topic: "homeassistant/temperature/set"
    temperature_state_topic: "homeassistant/climate/palazzetti/state"
    temperature_state_template: "{{ value_json.target_temp}}"
    current_temperature_topic: "homeassistant/climate/palazzetti/state"
    current_temperature_template: "{{ value_json.current_temp}}"
    fan_mode_command_topic: "homeassistant/fan/set"
    fan_mode_state_topic: "homeassistant/climate/palazzetti/state"
    fan_mode_state_template: "{{ value_json.fan_mode}}"
    action_topic: "homeassistant/climate/palazzetti/state"
    action_template: "{{ value_json.action}}"
    max_temp: 28
    min_temp: 18
